// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mSmYcSytipJFu7HGkZxBC4X-z3MU-o8',
    appId: '1:827690532017:web:eee1e0a72f7ffcc23e3690',
    messagingSenderId: '827690532017',
    projectId: 'grocery-store-499bb',
    authDomain: 'grocery-store-499bb.firebaseapp.com',
    storageBucket: 'grocery-store-499bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6sAg6MGcs4FD8XYa2rKw2rapvPpegQY',
    appId: '1:827690532017:android:7e50956c2d18781c3e3690',
    messagingSenderId: '827690532017',
    projectId: 'grocery-store-499bb',
    storageBucket: 'grocery-store-499bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-UXvJSF-6ZDyBfmOWo8CBGwtKH5tJis',
    appId: '1:827690532017:ios:bdb70ab94b0d70d83e3690',
    messagingSenderId: '827690532017',
    projectId: 'grocery-store-499bb',
    storageBucket: 'grocery-store-499bb.appspot.com',
    iosBundleId: 'com.example.adminSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-UXvJSF-6ZDyBfmOWo8CBGwtKH5tJis',
    appId: '1:827690532017:ios:e10d6b3e8b0aa2173e3690',
    messagingSenderId: '827690532017',
    projectId: 'grocery-store-499bb',
    storageBucket: 'grocery-store-499bb.appspot.com',
    iosBundleId: 'com.example.adminSide.RunnerTests',
  );
}
