// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsWkiU5V_NjDJrKDGr8MxVcvmamnnUYQ',
    appId: '1:1019694692270:web:92716b38e892506691ba3f',
    messagingSenderId: '1019694692270',
    projectId: 'fashion-store-29070',
    authDomain: 'fashion-store-29070.firebaseapp.com',
    storageBucket: 'fashion-store-29070.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gpAXI3s-4y2Ge0FfP107ZKdPQcXnuiU',
    appId: '1:1019694692270:android:c2e1e6df62d90c0791ba3f',
    messagingSenderId: '1019694692270',
    projectId: 'fashion-store-29070',
    storageBucket: 'fashion-store-29070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhn4skPtWsgznsU8o1tHMTf3YklxNpNg',
    appId: '1:1019694692270:ios:9a96ae1a383ed81f91ba3f',
    messagingSenderId: '1019694692270',
    projectId: 'fashion-store-29070',
    storageBucket: 'fashion-store-29070.appspot.com',
    iosBundleId: 'com.example.adminSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhn4skPtWsgznsU8o1tHMTf3YklxNpNg',
    appId: '1:1019694692270:ios:c3b41c3a26ad09f491ba3f',
    messagingSenderId: '1019694692270',
    projectId: 'fashion-store-29070',
    storageBucket: 'fashion-store-29070.appspot.com',
    iosBundleId: 'com.example.adminSide.RunnerTests',
  );
}
